In [35]:
import pandas as pd
import numpy as np
import csv


dataset = "adult.data"
df = pd.read_csv(dataset,sep=",",names=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country','ganancia'])
df = df.iloc[1:]
df.head()

delFilas = []

for i, r in df.iterrows():
    if r['workclass'] == ' ?':
        df.drop([i], inplace=True)
        
for i, r in df.iterrows():
    if r['occupation'] == ' ?':
        df.drop([i], inplace=True)
        
for i, r in df.iterrows():
    if r['native-country'] == ' ?':
        df.drop([i], inplace=True)

datos = df
datos


age          workclass  fnlwgt      education  education-num  \
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
30      23          Local-gov  190709     Assoc-acdm             12   
31      20            Private  266015   Some-college             10   
32      45            Private  386940      Bachelors             13   
...    ...                ...     ...            ...            ...   
32526   32            Private  211349           10th              6   
32527   22            Private  203715   Some-college             10   
32528   31            Private  292592        HS-grad              9   
32529   29            Private  125976        HS-grad              9   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32540   45          State-gov  252208        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

In [36]:
#Label Encoder
import numpy as np
from sklearn import preprocessing

# Sample input labels
#WorksClass

workclasslist = ['Federal-gov', 'Local-gov', 'Never-worked', 'Private', 'Self-emp-inc', 'Self-emp-not-inc', 'State-gov',
                 'Without-pay']

educationList= ['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th', 'Assoc-acdm', 'Assoc-voc', 'Bachelors',
                'Doctorate', 'HS-grad', 'Masters', 'Preschool', 'Prof-school', 'Some-college']

maritalStatusList= ['Divorced', 'Married-AF-spouse', 'Married-civ-spouse', 'Married-spouse-absent', 'Never-married',
                    'Separated', 'Widowed']

occupationList= ['Adm-clerical', 'Armed-Forces', 'Craft-repair', 'Exec-managerial', 'Farming-fishing', 'Handlers-cleaners',
                 'Machine-op-inspct', 'Other-service', 'Priv-house-serv', 'Prof-specialty', 'Protective-serv', 'Sales',
                 'Tech-support', 'Transport-moving']


relationshipList= ['Husband', 'Not-in-family', 'Other-relative', 'Own-child', 'Unmarried', 'Wife']

raceList= ['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other', 'White']

sexList= ['Female', 'Male']

nativeCountryList= ['Cambodia', 'Canada', 'China', 'Columbia', 'Cuba', 'Dominican-Republic', 'Ecuador', 'El-Salvador',
                    'England', 'France', 'Germany', 'Greece', 'Guatemala', 'Haiti', 'Holand-Netherlands', 'Honduras', 'Hong',
                    'Hungary', 'India', 'Iran', 'Ireland', 'Italy', 'Jamaica', 'Japan', 'Laos', 'Mexico', 'Nicaragua',
                    'Outlying-Us(Guam-USVI-etc)', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto-Rico', 'Scotland',
                    'South', 'Taiwan', 'Thailand', 'Trinadad&Tobago', 'United-States', 'Vietnam', 'Yugoslavia']


# Create label encoder and fit the labels

workclassCode = preprocessing.LabelEncoder()
workclassCode.fit(workclasslist)

educationCode = preprocessing.LabelEncoder()
educationCode.fit(educationList)


maritalStatusCode = preprocessing.LabelEncoder()
maritalStatusCode.fit(maritalStatusList)


occupationCode = preprocessing.LabelEncoder()
occupationCode.fit(occupationList)


relationshipCode = preprocessing.LabelEncoder()
relationshipCode.fit(relationshipList)


raceCode = preprocessing.LabelEncoder()
raceCode.fit(raceList)


sexCode = preprocessing.LabelEncoder()
sexCode.fit(sexList)


nativeCountryCode = preprocessing.LabelEncoder()
nativeCountryCode.fit(nativeCountryList)


# Print the mapping 
print("\nworkclassCode:")
for i, item in enumerate(workclassCode.classes_):
    print(item, '-->', i)
    
    print("\neducationCode:")
for i, item in enumerate(educationCode.classes_):
    print(item, '-->', i)
    
    print("\nmaritalStatusCode:")
for i, item in enumerate(maritalStatusCode.classes_):
    print(item, '-->', i)
    
    print("\noccupationCode:")
for i, item in enumerate(occupationCode.classes_):
    print(item, '-->', i)
    
    print("\nrelationshipCode:")
for i, item in enumerate(relationshipCode.classes_):
    print(item, '-->', i)
    
    print("\nraceCode:")
for i, item in enumerate(raceCode.classes_):
    print(item, '-->', i)
    
    print("\nsexCode:")
for i, item in enumerate(sexCode.classes_):
    print(item, '-->', i)
    
    print("\nnativeCountryCode:")
for i, item in enumerate(nativeCountryCode.classes_):
    print(item, '-->', i)
    
    
    
    
    
    
nuevaListWorkClass = []    
nuevaListeducation = []
nuevaListmaritalStatus = []
nuevaListoccupation = []
nuevaListrelationship = []
nuevaListrace = []
nuevaListsex = []
nuevaListnativeCountry = []
    

    
    
for i,r in df.iterrows():
    nuevaListWorkClass.append(r['workclass'].strip())   
    nuevaListeducation.append(r['education'].strip()) 
    nuevaListmaritalStatus.append(r['marital-status'].strip()) 
    nuevaListoccupation.append(r['occupation'].strip()) 
    nuevaListrelationship.append(r['relationship'].strip()) 
    nuevaListrace.append(r['race'].strip()) 
    nuevaListsex.append(r['sex'].strip()) 
    nuevaListnativeCountry.append(r['native-country'].strip()) 
    

    
workclassCode = workclassCode.transform(nuevaListWorkClass)
df['workclass'] = list(workclassCode)

educationCode = educationCode.transform(nuevaListeducation)
df['education'] = list(educationCode)

maritalStatusCode = maritalStatusCode.transform(nuevaListmaritalStatus)
df['marital-status'] = list(maritalStatusCode)

occupationCode = occupationCode.transform(nuevaListoccupation)
df['occupation'] = list(occupationCode)

relationshipCode = relationshipCode.transform(nuevaListrelationship)
df['relationship'] = list(relationshipCode)

raceCode = raceCode.transform(nuevaListrace)
df['race'] = list(raceCode)

sexCode = sexCode.transform(nuevaListsex)
df['sex'] = list(sexCode)

#nativeCountryCode = nativeCountryCode.transform(nuevaListnativeCountry)
#df['native-country'] = list(nativeCountryCode)

# Extraer la columna de native-country
inputs = np.array(df)
nativecountry= inputs[:,13]
#print(nativecountry)
# Create label encoder and fit the labels
encoder5 = preprocessing.LabelEncoder()
encoder5.fit(nativecountry)
# Print the mapping 
print("\nNative Country mapping:")
for i, item in enumerate(encoder5.classes_):
    print(item, '-->', i)

# Encode a set of labels using the encoder
encoded_values7 = encoder5.transform(nativecountry)
#print("\nLabels =", workclass)
#print("Encoded values =", list(encoded_values7))
df['native-country'] = encoded_values7

#################################################
# Extraer la columna de native-country
inputs = np.array(df)
ganancia= inputs[:,14]
#print(nativecountry)
# Create label encoder and fit the labels
encoder8 = preprocessing.LabelEncoder()
encoder8.fit(ganancia)
# Print the mapping 
print("\nGanancia Country mapping:")
for i, item in enumerate(encoder8.classes_):
    print(item, '-->', i)

# Encode a set of labels using the encoder
encoded_values8 = encoder8.transform(ganancia)
#print("\nLabels =", workclass)
#print("Encoded values =", list(encoded_values7))
df['ganancia'] = encoded_values8

df.head()





workclassCode:
Federal-gov --> 0

educationCode:
Local-gov --> 1

educationCode:
Never-worked --> 2

educationCode:
Private --> 3

educationCode:
Self-emp-inc --> 4

educationCode:
Self-emp-not-inc --> 5

educationCode:
State-gov --> 6

educationCode:
Without-pay --> 7

educationCode:
10th --> 0

maritalStatusCode:
11th --> 1

maritalStatusCode:
12th --> 2

maritalStatusCode:
1st-4th --> 3

maritalStatusCode:
5th-6th --> 4

maritalStatusCode:
7th-8th --> 5

maritalStatusCode:
9th --> 6

maritalStatusCode:
Assoc-acdm --> 7

maritalStatusCode:
Assoc-voc --> 8

maritalStatusCode:
Bachelors --> 9

maritalStatusCode:
Doctorate --> 10

maritalStatusCode:
HS-grad --> 11

maritalStatusCode:
Masters --> 12

maritalStatusCode:
Preschool --> 13

maritalStatusCode:
Prof-school --> 14

maritalStatusCode:
Some-college --> 15

maritalStatusCode:
Divorced --> 0

occupationCode:
Married-AF-spouse --> 1

occupationCode:
Married-civ-spouse --> 2

occupationCode:
Married-spouse-absent --> 3

occupationCo

age  workclass  fnlwgt  education  education-num  marital-status  \
1   50          5   83311          9             13               2   
2   38          3  215646         11              9               0   
3   53          3  234721          1              7               2   
4   28          3  338409          9             13               2   
5   37          3  284582         12             14               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   
5           3             5     4    0             0             0   

   hours-per-week  native-country  ganancia  
1              13              38         0  
2              40              38         0  
3              40              38         0  
4              40               4         0  
5              40              38         0

In [37]:
###############################################################################################################################
#Data_preprocessor

import numpy as np
from sklearn import preprocessing

input_data = np.array(df)

# Binarize data 
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)

# Print mean and standard deviation
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# Remove mean
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# Min max scaling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled data:\n", data_scaled_minmax)

# Normalize data
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


Binarized data:
 [[1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]]

BEFORE:
Mean = [3.84378834e+01 3.09943304e+00 1.89797557e+05 1.03338086e+01
 1.01212161e+01 2.58008687e+00 5.96004774e+00 1.41835483e+00
 3.67859156e+00 6.75673883e-01 1.09197198e+03 8.83754186e+01
 4.09312689e+01 3.63825138e+01 2.48930738e-01]
Std deviation = [1.31346644e+01 1.14080773e+00 1.05650993e+05 3.81228418e+00
 2.54994104e+00 1.49799331e+00 4.02942024e+00 1.60133642e+00
 8.34707374e-01 4.68122512e-01 7.40634388e+03 4.04298050e+02
 1.19799830e+01 6.10536536e+00 4.32393601e-01]

AFTER:
Mean = [ 1.11666475e-16 -7.51510668e-17  5.93669870e-17  5.24172802e-17
 -9.23486464e-17 -1.04598977e-16 -4.16982409e-17  9.78848535e-17
  1.37580636e-16 -2.23804118e-17 -1.08368310e-17  3.88712415e-17
  1.64672714e-16 -2.27102284e-16  1.01536394e-16]
Std deviation = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Min max scaled data:
 [[0.45205479 0.71428571 