In [1]:
import pandas as pd
import numpy as np
import csv


dataset = "adult.data"
df = pd.read_csv(dataset,sep=",",names=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country','ganancia'])
df = df.iloc[1:]
df.head()

delFilas = []

for i, r in df.iterrows():
    if r['workclass'] == ' ?':
        df.drop([i], inplace=True)
        
for i, r in df.iterrows():
    if r['occupation'] == ' ?':
        df.drop([i], inplace=True)
        
for i, r in df.iterrows():
    if r['native-country'] == ' ?':
        df.drop([i], inplace=True)

datos = df
datos


age          workclass  fnlwgt   education  education-num  \
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   

        marital-status          occupation    relationship    race      sex  \
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
5   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital-gain  capital-loss  hours-per-week  native-country ganancia  
1             0             0              13   United-States    <=50K  
2             0             0              40   United-States    <=50K  
3             0             0              40   United-States    <=50K  
4             0             0              40            Cuba    <=50K  
5             0             0              40   United-States    <=50K

In [1]:
#Label Encoder
import numpy as np
from sklearn import preprocessing

# Sample input labels
#WorksClass
input_labels = ["Private", "Self-emp-not-inc", "Self-emp-inc", "Federal-gov", "Local-gov", "State-gov", "Without-pay", "Never-worked"]

# Create label encoder and fit the labels
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

# Print the mapping 
print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)

# CODIFICACIÓN DE DATOS
test_labels = ['Private', 'Self-emp-not-inc', 'Self-emp-inc']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

# DECODIFICACIÓN DE DATOS
encoded_values = [3, 5, 4]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("Decoded labels =", list(decoded_list))


Label mapping:
Federal-gov --> 0
Local-gov --> 1
Never-worked --> 2
Private --> 3
Self-emp-inc --> 4
Self-emp-not-inc --> 5
State-gov --> 6
Without-pay --> 7

Labels = ['Private', 'Self-emp-not-inc', 'Self-emp-inc']
Encoded values = [3, 5, 4]

Encoded values = [3, 5, 4]
Decoded labels = ['Private', 'Self-emp-not-inc', 'Self-emp-inc']


In [2]:
###############################################################################################################################
#Data_preprocessor

import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])

# Binarize data 
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)

# Print mean and standard deviation
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# Remove mean
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# Min max scaling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled data:\n", data_scaled_minmax)

# Normalize data
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

BEFORE:
Mean = [ 3.775 -1.15  -1.3  ]
Std deviation = [3.12039661 6.36651396 4.0620192 ]

AFTER:
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation = [1. 1. 1.]

Min max scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]

L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]
